### ISSUE TITLE
Server Crash - Skyfactory 3 

### ISSUE THREAD

**Issue by cauliflower69** [CyclopsMC/IntegratedDynamics#100]
http://pastebin.com/eE3nag9E

Could not access field progress in class org.cyclops.integrateddynamics.tileentity.TileDryingBasin

**Comment by rubensworks** [comment]
@cauliflower69 Could you send me the full server log? There is log output in there that I need.

**Comment by Gunner76th** [comment]
Ill will try to get my log as well. We just had this crash when a player tried to process rotten flesh in the drying basin. 
here is our crash report for it as well. http://pastebin.com/xZcmfLCt

**Comment by Gunner76th** [comment]
[Log files.zip](https://github.com/CyclopsMC/IntegratedDynamics/files/681474/Log.files.zip)
If you need the older log files as well, please let me know @rubensworks

**Comment by Gunner76th** [comment]
After extensive testing of all known recipes for the drying basin, and using the dev build of Cyclops Core that @rubensworks supplied me, the OP crash has been resolved. Please use https://dl.bintray.com/cyclopsmc/dev/org/cyclops/cyclopscore/CyclopsCore/1.9.4-0.8.2-450/CyclopsCore-1.9.4-0.8.2-450.jar on your server, and your players will need to manually update their clients with this as well. If you or they have any issues in doing this, feel free to have them contact me on my Discord server https://discord.gg/0hQAXZIOgrb5RFRG and I or one of my Admins/Devs can assist them. 

Because the Dev 450 build has resolved the crash when using the drying basin, I recommend that this issue be marked closed, and not related to Integrated Dynamics as the fix was a code change in Cyclops Core and not Integrated Dynamics.

**Comment by rubensworks** [comment]
I'm still not sure that build actually resolves the issue, I just think the crash does not occur consistently.

**Comment by Gunner76th** [comment]
well for the time being we are going to stay with the dev build and see if it does crash. Before I posted my crash, it was consistently crashing every time he tried to process rotten flesh, 100% of the time. Sometimes it can be something as simple as a comma in the wrong spot or some other operator or even a spelling issue. 

But I will update if it does crash again with the dev build of the cyclops core. but for now, since we are unable to reproduce the previous crash we are considering this resolved.

**Comment by rubensworks** [comment]
@Gunner76th Your server admin probably enabled the Forge option to remove erroring tile entities, which would explain the constant console spam.

**Comment by Gunner76th** [comment]
Nope, I didnt. I am actually the senior admin for our group, and the only one maintaining the server at the moment. Here is our forge.cfg file

**Comment by Gunner76th** [comment]
[forge.cfg.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/682784/forge.cfg.txt)

**Comment by Gunner76th** [comment]
I never enable that function unless the dev for a mod that is having trouble specifically instructs me to, due to the fact that option can cause severe problems.

**Comment by rubensworks** [comment]
Fixed in CyclopsMC/CyclopsCore#33
New CyclopsCore release coming later today or tomorrow.
