### ISSUE TITLE
Server Hanging when a certain player logs off

### ISSUE THREAD

**Issue by jinkhya** [CyclopsMC/IntegratedDynamics#1411]
#### Issue type:

- :bug: Bug 
____

#### Short description:

Hello ! So this is kinda a weird one... We've had a problem with server hanging when a specific player disconnects from the server and we're trying to narrow it down. Today it generated a crash-log : https://gist.github.com/jinkhya/9ba485a2dc430983d1943fc6ad06b3be 
Hopefully you can decipher what caused the crash :sweat_smile: 
#### Steps to reproduce the problem:

Well... I can't tell you how to reproduce it, it only happens with one of our players :(
If you have an idea on what is causing it I can test things out though !

#### Expected behaviour:

To not make the server hang I suppose :)
____

#### Versions:

- This mod: 1.23.9
- Minecraft: 1.21.1
- Mod loader version:  Neoforge 21.1.72

#### Log file:
https://gist.github.com/jinkhya/351a1e357ccdff8cc11858de6c39a559

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I've had a look at this, and it looks like there is probably some race condition during chunk loading/unloading.

I'm not sure at the moment that ID is the cause of the problem.
It could very well be that there is some underlying problem (possibly through some other mod) that is causing this, and by chance ID could also be running into trouble because of this underlying problem every now and then.
This could explain this crashlog only happening sometimes, while the server simply keeps on hanging all of the other times.

I'll place this issue on-hold for now.
Should you learn about any additional information that could be relevant, please let me know.

**Comment by jinkhya** [comment]
Hello, 

The issue happened again today and I did a good bit of testing. I narrowed down the issue to be between ID and AE2. I copied the region file at fault into a world within an instance with those 2 mods (and their libraries) I'll give you the zip of the world if you want to have a look. It's definitely a weird issue : If I break everything from AE2 it fixes it, if I break everything from ID, it also fixes it. And those 2 mods aren't connected in any way so I don't understand lol. They are in the same chunk though.

To reproduce : 
- Make a 1.21.1 instance with AE2 + ID + dependencies
- Load the world I'm giving you and go to 4979 58 3317 coordinates
- Save and exit. The world is stuck at saving
- if you load it again and break AE2 or ID setup, you'll see that when you save and exit the world, it takes half a second and is fine.
 
[world.zip](https://github.com/user-attachments/files/17532629/world.zip)

If you need anything else lemme know !

**Comment by rubensworks** [comment]
I see, that's interesting.

**Comment by rubensworks** [comment]
While fixing #1415, I realized that this is exactly the same problem.
Since #1415 is fixed, this one can also be closed. (expect a new release soon)

**Comment by jinkhya** [comment]
Hello, so it looks like this issue is back unless it's something else causing it but it seems very similar.
A player on our server has ID and ae2 and when he logs off the server hangs. 

Playing craftoria modpack which has : 
ID 1.25.2
Neoforge 21.1.115

Is there any code change that would have reintroduced this?

Best regards,
Jin

**Comment by rubensworks** [comment]
> Is there any code change that would have reintroduced this?

Not as far as I know, no.

If you find the precise ID version in which the problem re-occurs, that could definitely help.
