### ISSUE TITLE
Minetweaker support doesn't work on Drying Basin?

### ISSUE THREAD

**Issue by Claycorp** [CyclopsMC/IntegratedDynamics#187]
``mods.integrateddynamics.DryingBasin.removeRecipesWithOutput(<minecraft:leather>);
mods.integrateddynamics.DryingBasin.removeRecipesWithOutput(<minecraft:hardened_clay>);
mods.integrateddynamics.DryingBasin.removeRecipesWithOutput(<minecraft:dirt:1>);``

All of these do not remove the recipe from the drying basin.
Here is the MineTweaker log https://gist.github.com/Claycorp/24b6790c0e2abace64cda78b0ac56abb

ID:  0.7.2
CT: 3.0.25

If there is something I am missing the Wiki is missing it also as that's where i got the info from.

**Comment by Claycorp** [comment]
This is a bug with the JEI integration. JEI shows the recipe but it doesn't exist.

**Comment by rubensworks** [comment]
@Claycorp Can you report this to the Minetweaker repo then? Sounds like something that should be fixed on their end.

**Comment by Claycorp** [comment]
Don't you add the Minetweaker support? Not sure what I'm reporting otherwise.

**Comment by rubensworks** [comment]
@Claycorp We add the Minetweaker support, but conflicts with JEI sounds like something that should be fixed on their end.

**Comment by Claycorp** [comment]
I highly doubt its a bug with minetweaker. Its either you missed something adding in the support or whoever adds the JEI info is messing it up. When I found issues with Better Beginnings they had to fix the recipes duplicating, thus I would assume that you aren't telling JEI to update.

**Comment by rubensworks** [comment]
Sounds similar to https://github.com/jaredlll08/ModTweaker/issues/437, I'll lurk at that issue to see how that'll be resolved.

**Comment by Claycorp** [comment]
That isn't the issue at all..... The JEI recipes are never updated. They aren't removed or added. None of your minetweaker scripts update JEI.

**Comment by rubensworks** [comment]
@Claycorp Note the comment on IC2 and Tinkers support: https://github.com/jaredlll08/ModTweaker/issues/437#issuecomment-286114316

**Comment by Claycorp** [comment]
There is a difference, Those mods are supported by MT itself and ModTweaker respectively. Not their own custom MT support.

I did some quick comparing to other peoples code and you don't have any JEI updates in yours anywhere.
[The MineTweaker API](https://github.com/jaredlll08/CraftTweaker/blob/master/MineTweaker3-API/src/main/java/minetweaker/MineTweakerAPI.java#L94)

[Better Beginnings](https://github.com/Leviathan143/betterbeginnings-MODIFIED/blob/1.10.2/src/main/java/net/einsteinsci/betterbeginnings/crafttweaker/KilnTweaker.java#L68)

[Underworld](https://github.com/Matryoshika/Underworld/blob/master/src/main/java/se/Matryoshika/Underworld/Integration/CraftTweaker/MTMetamorphicTableRecipes.java#L30) This was a totally random mod I found based off [this issue](https://github.com/jaredlll08/CraftTweaker/issues/183)

So... Again.... This isn't an issue with MT/CT/ModTweaker or any other tweaking/addon like I said before.....

**Comment by rubensworks** [comment]
As mentioned before, I planned to wait until jaredlll08/ModTweaker#437 is resolved, to see how that is fixed, as I will most likely have to do something similar.

But It looks like you already found some similar fixes, so I can start looking into that.

**Comment by rubensworks** [comment]
The latest dev build fixes the issue, had to rewrite a couple of things. Thanks for persisting :-)

**Comment by Claycorp** [comment]
It wasn't fixed FYI.
I finally figured out the exact issue. 
You have your own recipe stuff in the XML and Minetweaker it will still show the recipes that are in the XML even if you remove them via Minetweaker thus creating the recipes that you can see but don't work. So you need to do some magic to sync up whats removed in Minetweaker to the XML side.

**Comment by rubensworks** [comment]
@Claycorp Please send me your script so I can try to reproduce it.

**Comment by Claycorp** [comment]
[DryingBasin.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/1144271/DryingBasin.txt)

I then added this

[dryingbasin_convenience.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/1144275/dryingbasin_convenience.txt)

and they went away.

Files were renamed because Github dosn't allow .zs or .xml Just rename and its all good.

**Comment by rubensworks** [comment]
Thanks, will try to look into it soon.

**Comment by Claycorp** [comment]
Now that I know how to get rid of them no need to rush. It was getting annoying when people constantly ask "Why doesn't this recipe work?? Its in JEI thus it must work!"

**Comment by rubensworks** [comment]
It looks like that combination of files is not causing the issue after all.
Just loaded both of them, and the recipes seem to be removed correctly, also from JEI.

<img width="463" alt="schermafbeelding 2017-07-17 om 09 45 29" src="https://user-images.githubusercontent.com/440384/28259093-e457a758-6ad4-11e7-9c6e-d53d5066073f.png">

**Comment by Claycorp** [comment]
Remove the XML file. I added the XML and they went away, but if you remove it they should show up again even though the recipes don't exist.

**Comment by rubensworks** [comment]
Ah, like that. Don't understand why that would change a thing, but will try it out soon.
