### ISSUE TITLE
[1.9] Mod conflict with Modular Systems

### ISSUE THREAD

**Issue by b0bst3r** [CyclopsMC/IntegratedDynamics#36]
Added in Integrated Dynamics 1.9-0.3.8 and it causes the following crash: http://pastebin.com/UGsqiQDN

Remove Modular Systems and no crash occurs
Remove Integrated Dynamics and no crash occurs
Put them together and BOOM!!

Don't know who's problem this is @Dyonovan

**Comment by rubensworks** [comment]
Huh, that seems like a tile entity name scoping issue. I though those were handled automatically by Forge. I guess I'll have to look into it.

**Comment by b0bst3r** [comment]
Yeah I found the issue on Modular Systems github https://github.com/TeamCoS/Modular-Systems/issues/123

**Comment by Dyonovan** [comment]
Ive never seen this before either. Forge is supposed to take care of this when you register the tileentity

**Comment by Dyonovan** [comment]
Where are you registering your tile entities? I don't see any calls to GameRegistry.registerTileEntity?

**Comment by rubensworks** [comment]
@Dyonovan The tile registration is abstracted in CyclopsCore here: https://github.com/CyclopsMC/CyclopsCore/blob/master-1.9/src/main/java/org/cyclops/cyclopscore/config/configurabletypeaction/BlockAction.java#L94

But it looks like `GameRegistry#registerTileEntity` does _not_ take into account mod scoping. It's strange that I never had such an issue before...
It looks like we will have to rename all of our TE id's. Apparently the method `GameRegistry#registerTileEntityWithAlternatives` allows you to rename TE id's with backwards compatibility. I'll try to implement this ASAP.

**Comment by rubensworks** [comment]
Fixed in CyclopsMC/CyclopsCore@6a81ba413d752202074bffc3a9a49ab1d8492cfc

**Comment by b0bst3r** [comment]
Nope this still occurs.

CyclopsCore-1.9-0.5.9.jar
forge-1.9-12.16.1.1900-universal.jar

http://pastebin.com/E19pK2yS

**Comment by rubensworks** [comment]
@b0bst3r Try updating Modular systems once they fix the bug, I assume they will also have to make the change to solve the conflict.

**Comment by b0bst3r** [comment]
Yeah that's not likely to happen anytime soon unfortunately, but still need malisis fix anyway for Int Dyn, so at that point we will have to remove Mod Systems and probably Neotech since it's covered in bugs.

**Comment by Rongmario** [comment]
FOR REFERENCE: Disable the proxy block in IntDyn's config and the game should be able to run.
